version: '3.8'

services:
  blender:
    build:
      context: ./blender
      dockerfile: Dockerfile
    container_name: blender_cropcraft
    # security_opt:
    #   - seccomp:unconfined #optional
    environment:
      - PUID=1000 # 
      - PGID=1000 # 
      - TZ=America/Sao_Paulo # Time Zone
      # - SUBFOLDER=/ #optional
    networks:
      - blender_net
    # command:
    #   - blender --background
    volumes:
      - ./blender/src/config:/config
      - ./blender/cropcraft:/cropcraft
      - ./ros/weed_robot_simulation-master/gazebo_blender:/cropcraft/src/gazebo
      - ./ros2/src/gazebo_blender:/src/gazebo_blender
    ports:
      - 3000:8000
      - 3001:8001
    restart: unless-stopped
    
#  ros:
#    build:
#      context: ./ros
#      dockerfile: Dockerfile.ros
#    container_name: ros
#    networks:
#      - blender_net
#    depends_on:
#      - blender
#    environment:
#      - PYTHON_HOST=blender
#    volumes:
#      - ./ros/src:/root/catkin_ws/src/
#      - ./ros/src/weed_robot_simulation-master/gazebo_blender:/src/gazebo_blender

  # ros2:
  #   build:
  #     context: ./ros2
  #     dockerfile: Dockerfile
  #   container_name: ros2
  #   networks:
  #     - blender_net
  #   depends_on:
  #     - blender
  #   environment:
  #     - PYTHON_HOST=blender
  #   volumes:
  #     - ./ros2/src:/root/colcon_ws
  #     - ./ros2/src/gazebo_blender:/src/gazebo_blender

networks:
  blender_net:
    driver: bridge

