version: '3.8'

services:
  blender:
    build:
      context: ./blender
      dockerfile: Dockerfile.blender
    container_name: blender_cropcraft
    # security_opt:
    #   - seccomp:unconfined #optional
    environment:
      - PUID=1000 # 
      - PGID=1000 # 
      - TZ=America/Sao_Paulo # Time Zone
      # - SUBFOLDER=/ #optional
    networks:
      - blender_net
    volumes:
      - ./blender/src/config:/config
      - ./blender/cropcraft:/cropcraft
      - ./ros/weed_robot_simulation-master/gazebo_blender:/cropcraft/src/gazebo
      - ./gazebo/src/simulation:/cropcraft/src/gazebo

    restart: unless-stopped
    
  ros:
    build:
      context: ./ros
      dockerfile: Dockerfile.ros
    container_name: ros
    networks:
      - blender_net
    depends_on:
      - blender
    environment:
      - PYTHON_HOST=blender
    volumes:
      - ./ros/src:/root/catkin_ws/src/
      - ./ros/src/weed_robot_simulation-master/gazebo_blender:/src/gazebo_blender

  ros2:
    build:
      context: ./ros2
      dockerfile: Dockerfile.ros2
    container_name: ros2
#    networks:
#      - blender_net
#    depends_on:
#      - blender
#    environment:
#      - PYTHON_HOST=blender
    volumes:
      - ./ros2/src:/root/colcon_ws

networks:
  blender_net:
    driver: bridge
