# Dockerfile.blender

FROM linuxserver/blender

# Ensure snap binaries are in PATH
ENV PATH=$PATH:/snap/bin

# Start Blender in background
CMD ["blender", "--background", "--python-expr", "import bpy; bpy.ops.wm.quit_blender()"]