# Dockerfile.python

FROM python:3.10-slim

# Install dependencies
RUN apt update && apt install -y python3-pip

# Set working directory
WORKDIR /app

# Copy source code
COPY src /app/src

# Install Python dependencies
RUN pip install -r /app/src/requirements.txt

# Set the entrypoint command
CMD ["python3", "/app/src/cropcraft.py", "examples/test1.yaml"]

